Remove PreferenceManager.setDefaultValues()
That line caused Taide to hard crash with a ClassNotFoundException, but only on
the Z4 Tablet, not in the emulator. It did not seem to actually do anything,
since the settings got their default values anyway, so removing it should be
OK. More info from the log:

Caused by: android.view.InflateException: Binary XML file line #3: Error
inflating class preference-headers

Caused by: java.lang.ClassNotFoundException: Didn't find class
"android.preference.preference-headers" on path: DexPathList[[zip file
"/data/app/se.chalmers.taide-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64,
/system/lib64]]

Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class
loader; no stack available